id: 'bb262015-57db-49b7-9bcc-08dd9c3f3d0a'
name: 'C3-X-DB-DV'
description: 'This is my e-learning Project with the Databricks DataVault and Mart generator to practice for the course C3-X-DB-DV'
version: 'v1.5'
configuration:
  id: 'biGENIUS.Implementation.Generator.VaultAndMart.Spark.Databricks'
  version: '1.9.5'
sourceSystems:
  - id: '44e09da6-3b33-4f19-a50e-b9375ccc9981'
    name: 'MyFirstProject'
    isLinkedProject: true
    sourceSystemTypeId: '301305db-47c8-4d20-b2b2-5dbefbaf251d'
propertyValues:
  - propertyId: '59eca19a-3bec-4169-85fd-41331f6fac3a'
    value: 'true'
